# Generated by Django 3.2.6 on 2021-08-13 09:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NewsSources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('domain', models.CharField(max_length=100, null=True)),
                ('rss_url', models.URLField(blank=True, null=True)),
                ('article_selector', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=5, null=True)),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coingecko_id', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('homepage', models.URLField(null=True)),
                ('symbol', models.CharField(max_length=10)),
                ('image_url', models.CharField(blank=True, max_length=100, null=True)),
                ('proof_type', models.CharField(blank=True, max_length=100, null=True)),
                ('algorithm', models.CharField(blank=True, max_length=100, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('ath', models.FloatField(blank=True, null=True)),
                ('ath_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('categories', models.ManyToManyField(to='content.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('price_change_24h', models.FloatField(blank=True, null=True)),
                ('price_change_percent_24h', models.FloatField(blank=True, null=True)),
                ('volume_24h', models.FloatField(blank=True, null=True)),
                ('supply', models.FloatField(blank=True, null=True)),
                ('marketcap', models.FloatField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.project')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptopanic_id', models.IntegerField(blank=True)),
                ('cryptopanic_url', models.URLField(blank=True)),
                ('title', models.CharField(max_length=500, null=True)),
                ('type', models.CharField(max_length=20)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('votes', models.JSONField(blank=True, null=True)),
                ('article_url', models.URLField(null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('projects', models.ManyToManyField(to='content.Project')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.newssources')),
            ],
        ),
    ]
