# Generated by Django 3.2.6 on 2021-08-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['published_at'], 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='newssources',
            options={'verbose_name_plural': 'NewsSources'},
        ),
        migrations.AlterModelOptions(
            name='prices',
            options={'verbose_name_plural': 'Prices'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='news',
            name='expert_level',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('INTERMEDIATE', 'Intermediate'), ('PRO', 'Pro')], default='PRO', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PUBLISHED', 'Placed in feed')], default='RECEIVED', max_length=50),
        ),
    ]
