# Generated by Django 3.2.6 on 2021-08-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20210813_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PUBLISHED', 'Placed in feed'), ('IGNORE', 'Ignore post')], default='RECEIVED', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
