# Generated by Django 3.2.6 on 2021-08-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='categories',
            field=models.ManyToManyField(blank=True, to='content.NewsCategory'),
        ),
        migrations.AlterField(
            model_name='news',
            name='projects',
            field=models.ManyToManyField(blank=True, to='content.Project'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, to='content.Tag'),
        ),
    ]
