# Generated by Django 3.2.6 on 2021-08-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20210814_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coingecko_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='marketcap_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
