# Generated by Django 3.2.6 on 2021-08-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20210815_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='community_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='developer_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='genesis_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='liquidity_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
