# Generated by Django 3.2.6 on 2021-08-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20210815_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sentiment_negative',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sentiment_positive',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
