# Generated by Django 3.2.6 on 2021-08-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20210815_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='sentiment_negative',
            new_name='sentiment_negative_percentage',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='sentiment_positive',
            new_name='sentiment_positive_percentage',
        ),
    ]
