# Generated by Django 3.2.6 on 2021-08-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20210815_0747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prices',
            options={'ordering': ['project__coingecko_rank'], 'verbose_name_plural': 'Prices'},
        ),
        migrations.RemoveField(
            model_name='prices',
            name='supply',
        ),
        migrations.AlterField(
            model_name='project',
            name='ath_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
