# Generated by Django 3.2.6 on 2021-12-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20211110_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='high_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prices',
            name='low_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prices',
            name='marketcap_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prices',
            name='marketcap_change_percent_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prices',
            name='marketcap_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prices',
            name='price_change_percent_1h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prices',
            name='price_change_percent_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prices',
            name='volume_1h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prices',
            name='volume_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prices',
            name='volume_change_percent_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ath_change_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='atl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='atl_change_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='atl_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='circulating_supply',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='max_supply',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_supply',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='symbol',
            field=models.CharField(max_length=100),
        ),
    ]
