# Generated by Django 3.2.6 on 2021-12-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20211203_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssources',
            name='manual_import',
            field=models.BooleanField(default=False),
        ),
    ]
