# Generated by Django 3.2.6 on 2021-12-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_auto_20211224_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cryptopanic_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='cryptopanic_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
