# Generated by Django 3.2.6 on 2022-04-03 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20211224_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='telegram_status',
        ),
        migrations.AlterField(
            model_name='newssources',
            name='article_selector',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='newssources',
            name='article_selector_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='newssources',
            name='domain',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PublishedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.news')),
            ],
            options={
                'verbose_name_plural': 'PublishedLog',
            },
        ),
    ]
