# Generated by Django 3.2.6 on 2022-09-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20220403_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coinmarketcap_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
